version: "3"

services:
    influxdb:
        container_name: influxdb
        image: influxdb:1.7.1-alpine
        volumes:
            - ./influxdb/etc:/etc/influxdb
            - influxdb-lib:/var/lib/influxdb
        environment:
            - INFLUXDB_ADMIN_USER=root
            - INFLUXDB_ADMIN_PASSWORD=5up3rS3cr3t
        ports:
            - 8083:8083
            - 8086:8086
        privileged: true

    grafana:
        container_name: grafana
        image: grafana/grafana:latest
        volumes:
            - ./grafana/etc:/etc/grafana:ro
            - grafana-lib:/var/lib/grafana
            - grafana-log:/var/log/grafana
        links:
            - influxdb:influxdb
        environment:
            - GF_INSTALL_PLUGINS=grafana-clock-panel
        ports:
            - 3000:3000
        depends_on:
            - influxdb
        privileged: true

volumes:
  influxdb-lib:
    external: false

  grafana-lib:
    external: false

  grafana-log:
    external: false
